CREATE TABLE pessoa
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_pessoa     VARCHAR(31),
    nome            VARCHAR(100)                            NOT NULL,
    celular         VARCHAR(255),
    telefone        VARCHAR(255),
    email           VARCHAR(255)                            NOT NULL,
    cep             VARCHAR(10)                             NOT NULL,
    logradouro      VARCHAR(100)                            NOT NULL,
    numero          VARCHAR(255)                            NOT NULL,
    complemento     VARCHAR(255),
    cidade          VARCHAR(50)                             NOT NULL,
    bairro          VARCHAR(50)                             NOT NULL,
    estado          VARCHAR(50)                             NOT NULL,
    cpf             VARCHAR(255),
    cnpj            VARCHAR(255),
    cpf_responsavel VARCHAR(255),
    CONSTRAINT pk_pessoa PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE pessoa
    ADD CONSTRAINT uc_pessoa_cnpj UNIQUE (cnpj);

ALTER TABLE pessoa
    ADD CONSTRAINT uc_pessoa_cpf UNIQUE (cpf);

ALTER TABLE pessoa
    ADD CONSTRAINT uc_pessoa_cpfresponsavel UNIQUE (cpf_responsavel);

ALTER TABLE pessoa
    ADD CONSTRAINT uc_pessoa_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_login UNIQUE (login);